production:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  pool: 5
  username: panda3
  password: sampleapp3


development:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  pool: 5
  username: panda3
  password: sampleapp

test:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  pool: 5
  username: panda3
  password: sampleapp