production:
  adapter: postgresql
  encoding: unicode
  database: sampleapp
  pool: 5
  username: panda3
  password: sampleapp


development:
  adapter: postgresql
  encoding: unicode
  database: sampleapp_development
  pool: 5
  username: panda3
  password: sampleapp

test:
  adapter: postgresql
  encoding: unicode
  database: sampleapp_test
  pool: 5
  username: panda3
  password: sampleapp